
use_amp: True
use_ema: True
ema:
  type: ModelEMA
  decay: 0.9999
  warmups: 1000
  start: 0


find_unused_parameters: False 

epoches: 120
clip_max_norm: 0.1

optimizer:
  type: AdamW
  params: 
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.00002
    -
      params: '^(?=.*backbone)(?=.*norm|bn).*$'
      lr: 0.00002
      weight_decay: 0.
    - 
      params: '^(?=.*encoder(?=.*bias|.*norm.*weight)).*$'
      weight_decay: 0.
    -
      params: '^(?=.*decoder(?=.*bias|.*norm.*weight)).*$'
      weight_decay: 0.

  lr: 0.0002
  betas: [0.9, 0.999]
  weight_decay: 0.000065


lr_scheduler:
  type: MultiStepLR
  milestones: [60, 100]
  gamma: 0.8

lr_warmup_scheduler:
  type: LinearWarmup
  warmup_duration: 500

