task: detection

num_classes: 10
remap_mscoco_category: True

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /hy-tmp/Datasets/VisDrone2019/VisDrone2019-DET-train/images
    ann_file: /hy-tmp/Datasets/VisDrone2019/Anno/VisDrone2019-DET_train_coco.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 8
  num_workers: 4
  drop_last: True


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /hy-tmp/Datasets/VisDrone2019/VisDrone2019-DET-val/images
    ann_file: /hy-tmp/Datasets/VisDrone2019/Anno/VisDrone2019-DET_val_coco.json
    transforms:
      type: Compose
      ops: ~

  shuffle: False
  batch_size: 8
  num_workers: 4
  drop_last: False